#!/bin/bash

if [ "$1" = "" ]; then echo "format: `basename $0` ms"; exit; fi

r=`uname -r | head --bytes 1`
if [ "$r" = "4" ]; then i2c=0; else i2c=10; fi

echo "removing /dev/shm/out.*.raw"
rm -f /dev/shm/out.*.raw

if [ "$2" = "" ]; then fps=41; else fps=$2; fi
echo "capturing frames for ${1}ms with ${fps}fps requested"
raspiraw -md 2 -y $i2c -vf -hf -t $1 -ts tstamps.dirty -hd0 hd0.32k -sr 1 -o /dev/shm/out.%04d.raw 2>/dev/null >/dev/null

grep -v ",0$" tstamps.dirty | grep -v ",-[0-9]*$" > tstamps.csv

us=`cut -f1 -d, tstamps.csv | sort -n | uniq -c | sort -n | tail -1 | cut -b9-`
l=`wc --lines tstamps.csv | cut -f1 -d\ `
echo -e "$l frames were captured\nmajority framerate $((1000000 / $us))fps" 

echo "frame delta time[us] distribution"
cut -f1 -d, tstamps.csv | sort -n | uniq -c

D=`echo "0123456789" | sed "s/\`echo $((1000000/$fps)) | cut -b1\`//"`

echo "after skip frame indices (middle column)"
grep "^[$D]" tstamps.csv | sed "s/^/> /"

skips=`grep "^[$D]" tstamps.csv | wc --lines | cut -f1 -d\ `
stamps=`wc --lines tstamps.csv | cut -f1 -d\ `
per=`expr \( 100 \* $skips \) / \( $skips + $stamps \)`
echo "$per% frame skips"

fst=`head -1 tstamps.csv | cut -f3 -d,`
lst=`tail -1 tstamps.csv | cut -f3 -d,`
dif=`expr $lst - $fst`
dif2=`expr $dif / 2`
avg=`expr \( 1000000 \* \( $l - 1 \) + $dif2 \) / $dif`
echo "average framerate ${avg}fps"
