#!/bin/bash

if [ "$1" = "" ]; then echo "format: `basename $0` ms"; exit; fi

hd () {
  echo -n $1 | sed "s/\(.\)/\1\xa/g" > /tmp/n
  local l=`echo -n $1 | wc --bytes`
  echo -n `head -n $(($l-2)) /tmp/n` | sed "s/ //g"
  echo -n .`tail -n -2 /tmp/n` | sed "s/ //g"
}

r=`uname -r | head --bytes 1`
if [ "$r" = "4" ]; then i2c=0; else i2c=10; fi

echo "removing /dev/shm/out.*.raw"
rm -f /dev/shm/out.*.raw

if [ "$2" = "" ]; then fps=11.38; else fps=$2; fi
echo "capturing frames for ${1}ms with ${fps}fps requested"
raspiraw -md 3 -y $i2c -vf -hf -t $1 --fps $fps -ts tstamps.dirty -hd0 hd0.32k -sr 1 -o /dev/shm/out.%04d.raw 2>/dev/null >/dev/null

grep -v ",0$" tstamps.dirty | grep -v ",-[0-9]*$" > tstamps.csv

us=`cut -f1 -d, tstamps.csv | sort -n | uniq -c | sort -n | tail -1 | cut -b9-`
l=`wc --lines tstamps.csv | cut -f1 -d\ `
echo -en "$l frames were captured\nmajority framerate "
hd $((100000000 / $us))
echo "fps" 

echo "frame delta time[us] distribution"
cut -f1 -d, tstamps.csv | sort -n | uniq -c

D=`echo "0123456789" | sed "s/\`echo $us | cut -b1\`//"`

echo "after skip frame indices (middle column)"
grep "^[$D]" tstamps.csv | sed "s/^/> /"

skips=`grep "^[$D]" tstamps.csv | wc --lines | cut -f1 -d\ `
stamps=`wc --lines tstamps.csv | cut -f1 -d\ `
per=`expr \( 100 \* $skips \) / \( $skips + $stamps \)`
echo "$per% frame skips"

fst=`head -1 tstamps.csv | cut -f3 -d,`
lst=`tail -1 tstamps.csv | cut -f3 -d,`
dif=`expr $lst - $fst`
dif2=`expr $dif / 2`
avg=`expr \( 100000000 \* \( $l - 1 \) + $dif2 \) / $dif`
echo -n "average framerate "
hd ${avg}
echo "fps"
