#!/bin/bash

echo This does not work as is, use 210fps 640x416_s instead
exit 

if [ "$1" = "" ]; then echo "format: `basename $0` ms"; exit; fi

echo "removing /dev/shm/out.*.raw"
rm -f /dev/shm/out.*.raw

fps=180
echo "capturing frames for ${t}ms with $fps requested"
raspiraw -md 7 -t $1 -ts tstamps.csv -hd0 hd0.32k -h 240 --vinc 1F --fps $fps -r "380A,00F0;3802,78;3806,06AF" -sr 1 -o /dev/shm/out.%04d.raw 2>/dev/null >/dev/null

us=`cut -f1 -d, tstamps.csv | sort -n | uniq -c | sort -n | tail -1 | cut -b9-`
l=`ls -l /dev/shm/out.*.raw | wc --lines`
echo "$l frames were captured at $((1000000 / $us))fps" 

echo "frame delta time[us] distribution"
cut -f1 -d, tstamps.csv | sort -n | uniq -c

echo "after skip frame indices (middle column)"
grep "^[1-46-9]" tstamps.csv
